spring.application.name=souqly

spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000
spring.ecom.app.jwtCookieName=springBootEcom
spring.ecom.app.cookiePath=/api


spring.datasource.url=jdbc:mysql://localhost:3306/souqly?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG

# Stripe API Keys
# Replace with your actual Stripe secret key

#stripe.api.key=sk_test_

# Stripe Webhook Secret
# Replace with your actual webhook signing secret
# You can get this from your Stripe dashboard webhook settings
#stripe.webhook.secret=whsec_

file.upload-dir=D:\\souqly-uploads\\images\\

#spring.web.resources.static-locations=file:///D:/media/